name: Code quality checks

on:
  workflow_call:
  push:
    branches: [ main ]

jobs:
  check-code:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.17.0'

    - name: Run pre-commit checks
      uses: pre-commit/action@v2.0.3
